// electron-builder afterPack hook (electron-builder.json → "afterPack").
//
// Linux only: turn the packaged executable into a LAUNCHER SCRIPT.
//
// Why: on SteamOS the shell has to run with `--no-sandbox --no-zygote
// --disable-dev-shm-usage` (see main.cjs, "Steam Deck"), and Chromium reads
// those two before any JavaScript runs — `app.commandLine.appendSwitch`
// silently does nothing for them. Every good Deck launch so far had the
// flags typed into Steam's Launch Options by hand; an empty field stalled
// into a minute-long black splash and software rendering. So the thing
// Steam starts is a tiny POSIX sh script that detects SteamOS and `exec`s
// the real binary with the flags already on its command line. `exec`
// replaces the script's process, so Steam still tracks exactly one process
// and the overlay/"running" state behave as before.
//
// The script keeps the binary's old name (`zoomies-desktop`) so an existing
// non-Steam shortcut on a Deck keeps working after an in-place update; the
// real Electron binary becomes `zoomies-desktop.bin` next to it. Electron
// locates resources/ relative to the executable's directory, so the rename
// is invisible to it. On a regular Linux desktop the script adds nothing
// and the sandbox stays on.
const fs = require("node:fs");
const path = require("node:path");

const LAUNCHER = `#!/bin/sh
# Zoomies GP — Linux launcher (generated by desktop/after-pack.cjs).
# Runs the real binary (zoomies-desktop.bin) next to this file. On SteamOS /
# Steam Deck it adds the Chromium flags the game needs there, which must be
# on the command line before the process starts (typing them into Steam's
# Launch Options is no longer necessary).
here=$(cd "$(dirname "$0")" && pwd)
bin="$here/zoomies-desktop.bin"
deck=""
[ -n "$SteamDeck" ] && deck="env:SteamDeck"
[ -z "$deck" ] && [ -n "$SteamGamepadUI" ] && deck="env:SteamGamepadUI"
if [ -z "$deck" ]; then
  case "$XDG_CURRENT_DESKTOP $XDG_SESSION_DESKTOP" in
    *[Gg]amescope*) deck="env:gamescope" ;;
  esac
fi
if [ -z "$deck" ] && [ -r /etc/os-release ] && grep -Eq '^(ID|ID_LIKE)=.*steamos' /etc/os-release; then
  deck="os-release"
fi
[ -z "$deck" ] && [ -e /etc/steamos-release ] && deck="steamos-release"
if [ -z "$deck" ]; then
  # Unprivileged user namespaces off = Chromium's sandbox can't start on
  # ANY Linux without the SUID helper, which an extracted tarball lacks.
  for f in /proc/sys/kernel/unprivileged_userns_clone /proc/sys/user/max_user_namespaces; do
    if [ -r "$f" ] && [ "$(cat "$f" 2>/dev/null)" = "0" ]; then deck="no-userns"; fi
  done
fi
if [ -n "$deck" ]; then
  case " $* " in
    *" --no-sandbox "*) ;;
    *) set -- "$@" --no-sandbox --no-zygote --disable-dev-shm-usage ;;
  esac
  ZOOMIES_LAUNCHER="$deck"
  export ZOOMIES_LAUNCHER
fi
exec "$bin" "$@"
`;

exports.default = async function afterPack(context) {
  if (context.electronPlatformName !== "linux") return;
  const exe = context.packager.executableName || "zoomies-desktop";
  const dir = context.appOutDir;
  const binPath = path.join(dir, exe);
  const realPath = path.join(dir, `${exe}.bin`);
  if (!fs.existsSync(binPath)) {
    console.warn(`  • after-pack: ${exe} not found in ${dir}, launcher not written`);
    return;
  }
  fs.renameSync(binPath, realPath);
  fs.writeFileSync(binPath, LAUNCHER.replace(/zoomies-desktop\.bin/g, `${exe}.bin`), { mode: 0o755 });
  fs.chmodSync(binPath, 0o755);
  console.log(`  • after-pack: ${exe} is now the SteamOS-aware launcher (binary → ${exe}.bin)`);
};
